@serverUrl = http://localhost:3310

@serverUrl =https://fake-json-server-janet.herokuapp.com

### 查詢 post
GET {{serverUrl}}/posts


### 查詢 post 單筆
GET {{serverUrl}}/posts/1


### 新增 post 資料
POST {{serverUrl}}/posts
content-type: application/json

{
    "title": "first post",
    "author": "janet",
    "body": "content"
}

### 修改 post 資料

PUT {{serverUrl}}/posts/7
content-type: application/json

{
    "title": "first post",
    "author": "janet",
    "body": "content"
}

### 刪除 post 資料

Delete {{serverUrl}}/posts/4


#######################################################


### 註冊
POST {{serverUrl}}/register
content-type: application/json

{
    "nickname": "janet",
    "username": "janet",
    "password": "janet123"
}



### 登入
POST {{serverUrl}}/login
content-type: application/json

{
    "username": "janet",
    "password": "janet123"
}


###

#######################################################

### 查詢 news
GET {{serverUrl}}/news
